apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocerystore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grocerystore
  template:
    metadata:
      labels:
        app: grocerystore
    spec:
      containers:
        - name: grocerystore
          image: myacr003.azurecr.io/grocerystore:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: acr-secret
