# kubernetes/grocerystore-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: grocerystore-service
spec:
  selector:
    app: grocerystore
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
