apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "GroceryStore.fullname" . }}
  labels:
    {{- include "GroceryStore.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "GroceryStore.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "GroceryStore.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: APPLICATIONINSIGHTS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: app-insights-secrets
                  key: connectionString
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets[0].name }}
