apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "GroceryStore.fullname" . }}
  labels:
    {{- include "GroceryStore.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "GroceryStore.selectorLabels" . | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "GroceryStore.selectorLabels" . | nindent 4 }}
    spec:
      serviceAccountName: {{ include "GroceryStore.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            {{- range .Values.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
