apiVersion: v1
kind: Service
metadata:
  name: {{ include "grocerystore.fullname" . }}
  labels:
    {{- include "grocerystore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ include "grocerystore.name" . }}
