replicaCount: 2

image:
  repository: myacr003.azurecr.io/grocerystore
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

env:
  - name: APPLICATIONINSIGHTS_CONNECTION_STRING
    value: "InstrumentationKey=YOUR_INSTRUMENTATION_KEY"

imagePullSecrets:
  - name: acr-secret

serviceAccount:
  create: true
  name: ""
