name: Build, Push to ACR, and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Log in to Azure Container Registry
        run: echo ${{ secrets.AZURE_ACR_PASSWORD }} | docker login ${{ secrets.AZURE_ACR_NAME }}.azurecr.io -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/grocerystore:latest .
          docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/grocerystore:latest

      - name: Logout from Azure Container Registry
        run: docker logout ${{ secrets.AZURE_ACR_NAME }}.azurecr.io

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1

      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      - name: Create kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Check if Kubernetes secret exists
        id: check-secret
        run: |
          if kubectl get secret acr-secret; then
            echo "SECRET_EXISTS=true" >> $GITHUB_ENV
          else
            echo "SECRET_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Create Kubernetes secret for ACR if not exists
        if: env.SECRET_EXISTS == 'false'
        run: |
          kubectl create secret docker-registry acr-secret \
            --docker-server=${{ secrets.AZURE_ACR_NAME }}.azurecr.io \
            --docker-username=${{ secrets.AZURE_ACR_USERNAME }} \
            --docker-password=${{ secrets.AZURE_ACR_PASSWORD }} \
            --docker-email=<your-email>

      - name: Apply Kubernetes deployment
        run: kubectl apply -f deployment.yml

      - name: Describe deployment for debugging
        run: kubectl describe deployment grocerystore

      - name: Get pod names
        id: get-pods
        run: |
          kubectl get pods -o jsonpath='{.items[*].metadata.name}'

      - name: Describe and get logs for each pod
        run: |
          for pod in $(echo ${{ steps.get-pods.outputs.result }}); do
            echo "Describing pod $pod"
            kubectl describe pod $pod
            echo "Logs for pod $pod"
            kubectl logs $pod --all-containers=true
          done

      - name: Check node resources
        run: kubectl describe nodes

      - name: Check for image pull secrets
        run: kubectl get secret acr-secret -o yaml

      - name: Force delete old pods
        run: |
          for pod in $(kubectl get pods -o jsonpath='{.items[?(@.status.phase=="Terminating")].metadata.name}'); do
            kubectl delete pod $pod --grace-period=0 --force
          done

      - name: Update Kubernetes deployment image
        run: |
          kubectl set image deployment/grocerystore grocerystore=${{ secrets.AZURE_ACR_NAME }}.azurecr.io/grocerystore:latest
          kubectl rollout status deployment/grocerystore --timeout=300s
