name: Build, Push to ACR, and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Build with Maven
      run: mvn clean install

    - name: Log in to Azure Container Registry
      run: echo ${{ secrets.AZURE_ACR_PASSWORD }} | docker login ${{ secrets.AZURE_ACR_NAME }}.azurecr.io -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/grocerystore:latest .
        docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/grocerystore:latest

    - name: Logout from Azure Container Registry
      run: docker logout ${{ secrets.AZURE_ACR_NAME }}.azurecr.io

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v1

    - name: Create kubeconfig
      run: echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/grocerystore grocerystore=${{ secrets.AZURE_ACR_NAME }}.azurecr.io/grocerystore:latest
        kubectl rollout status deployment/grocerystore
